name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:
    name: CI with OTP-${{ matrix.otp }}
    strategy:
      fail-fast: false
      matrix:
        otp: ["27", "26", "25", "24"]

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install OTP-${{ matrix.otp }}
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: "3.18.0"
          version-type: strict

      - name: Install elvis
        run: |
          sudo apt-get update
          sudo apt-get -y install curl
          sudo curl https://github.com/inaka/elvis/releases/download/4.0.0/elvis -o /usr/bin/elvis
          sudo chmod +x /usr/bin/elvis
          
      - name: Compile
        run: rebar3 compile
      - name: Cache dialyzer
        uses: actions/cache@v4
        env:
          cache-name: dialyzer-plt-cache
        with:
          path: _build/
          key: ${{ runner.os }}-rebar-build-${{ env.cache-name }}-otp-${{ matrix.otp }}-${{ hashFiles('rebar.lock') }}
      - name: Run dialyzer
        run: rebar3 dialyzer
      - name: Run linter
        run: elvis rock --config elvis.config
      - name: Run tests
        run: rebar3 eunit --cover
      - name: Run cover
        run: rebar3 cover --verbose -m 100
